services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./environment/postgresql.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/back_app:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./environment/django.env
